replace accuracy_np() with accuracy() to fix:
TypeError: eq received an invalid combination of arguments - got (torch.cuda.LongTensor), but expected one of:

(int value)
didn’t match because some of the arguments have invalid types: (!torch.cuda.LongTensor!)
(torch.LongTensor other)
didn’t match because some of the arguments have invalid types: (!torch.cuda.LongTensor!)
￼