Fix bug for backwards=True when creating a LanguageModelLoader (#909)
* Fix bug for backwards=True when creating a LanguageModelLoader

Currently it fails with the following error:
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.
A simple fix is to copy the data so that it is no longer a view.

* Avoid dependency on spacy models for the test by adding a DummyTokenizer